version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Use environment variable for DB password
      MYSQL_DATABASE: ${DB_NAME} # Use environment variable for DB name
      MYSQL_USER: ${DB_USER} # Use environment variable for DB user
      MYSQL_PASSWORD: ${DB_PASSWORD} # Use environment variable for DB password
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mbrms-network

volumes:
  mysql_data:
    driver: local

networks:
  mbrms-network:
    driver: bridge
